name:                tennis-kata
version:             0.1.0.0
github:              "lvaylet/tennis-kata"
license:             BSD3
author:              "Laurent VAYLET"
maintainer:          "laurent.vaylet@gmail.com"
copyright:           "2019 Laurent VAYLET"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lvaylet/tennis-kata#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tennis-kata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-kata

tests:
  tennis-kata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-kata
    - hspec
